version: "3"
services:

  np:
    build:
      context: .
      args:
        CENTOS_VERSION: ${CENTOS_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
    volumes:
      - ${SOURCE_DIR}:/home/wwwroot/:rw
      - ${NGINX_CONF_VHOST_DIR}:/usr/local/nginx/conf/vhost:rw
      - ${NGINX_LOG_DIR}:/home/wwwlogs/:rw
      - ${PHP_FPM_CONF_FILE}:/usr/local/php/etc/php-fpm.conf:rw
    privileged: true
    links:
      - mysql:mysql
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    privileged: true
    volumes:
      # - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
      - ${MYSQL_INITDB_FILE}:/docker-entrypoint-initdb.d/init_db.sql
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - "${PHPMYADMIN_HOST_PORT}:80"
      networks:
        - default
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306

networks:
  default:
